### ISSUE TITLE
Very hard to do minor adjustments to crop area when zooming in

### ISSUE THREAD

**Issue by fawkeswei** [benedom/SwiftyCrop#10]
When zooming in the image doesn't smoothly follow the fingers like how Photos.app does. Instead zooms in super fast to max `maxMagnificationScale`. Very hard to do minor adjustments to crop area.

**Comment by benedom** [comment]
Added as feature. Please review @fawkeswei
https://github.com/benedom/SwiftyCrop/pull/11
