### ISSUE TITLE
Crop area is not displayed in a sheet view

### ISSUE THREAD

**Issue by pavelpugachh** [benedom/SwiftyCrop#13]
Hi!

When I use SwiftyCropView inside a sheet view like in the picture below, the crop area is almost always not displayed (but has been shown a few times).

<img width="515" alt="Screenshot 2024-05-18 at 16 08 31" src="https://github.com/benedom/SwiftyCrop/assets/140705830/00d7ddf9-1c33-4fdd-b4c2-a4005fbab675">

But it works fine if I use it in a sheet view hierarchy like this.

<img width="495" alt="Screenshot 2024-05-18 at 16 10 44" src="https://github.com/benedom/SwiftyCrop/assets/140705830/e4a8aa67-9568-484f-b5bf-cae6de6fdc6c">

**Comment by benedom** [comment]
Hi, can you specify the issue a little bit more?

- Device you are using
- iOS-Version
- Swift-Version
- Xcode-Version

Does the issue also persist when you use the demo of SwiftyCrop? In the demo it is presented as `fullScreenCover` just like in your example.

**Comment by pavelpugachh** [comment]
- iPhone 14 Pro
- 17.4.1 (real device) / 17.2 (simulator)
- Swift 5
- Xcode 15.3 (15E204a)

To reproduce the issue:

1. Create view just like in the demo
2. Display created view using .sheet() modifier

When I use it like in the demo it's OK.

**Comment by benedom** [comment]
It seems that SwiftUI is having problems displaying the mask of the ZStack when using the .sheet modifier. To solve this you can wrap the SwiftyCropView inside a NavigationView or NavigationStack when presented. This will show the cropping mask.

I suggest something like this:

```
.sheet(isPresented: $showImageCropper) {
            NavigationView {
                if let selectedImage = selectedImage {
                    SwiftyCropView(
                        imageToCrop: selectedImage,
                        maskShape: selectedShape,
                        configuration: SwiftyCropConfiguration(
                            maxMagnificationScale: maxMagnificationScale,
                            maskRadius: maskRadius,
                            cropImageCircular: cropImageCircular,
                            rotateImage: rotateImage,
                            zoomSensitivity: zoomSensitivity
                        )
                    ) { croppedImage in
                        // Do something with the returned, cropped image
                        self.selectedImage = croppedImage
                    }
                    .interactiveDismissDisabled()
                }
            }
        }
```

**Comment by pavelpugachh** [comment]
I solved it the next way:

`.fullScreenCover(isPresented: $showPhotoCropper, onDismiss: {
     self.photoCropperWillAppear = false
          }) {
               VStack{
                    if let photoToCrop = self.photoToCrop, self.photoCropperWillAppear {
                       SwiftyCropView(
                            imageToCrop: photoToCrop,
                            maskShape: .square,
                            configuration: SwiftyCropConfiguration(maxMagnificationScale: 2, maskRadius: self.vehicleImageCropHeight, rotateImage: false)
                        ) { croppedPhoto in
                            self.croppedPhoto = croppedPhoto
                        }
                    }
                }
               .uiKitViewWillAppear { self.photoCropperWillAppear = true }
     }`

Here `.uiKitViewWillAppear` works the same as `UIViewController.viewWillAppear()`. Perhaps this will help you solve the problem if you init mask when `viewWillAppear` is called. I'm not sure, I haven't looked at the code :)

**Comment by g3rd** [comment]
**FYI:** the bug is still present with the `NavigationStack` you must use a `NavigationView`

**Comment by benedom** [comment]
@g3rd I will add this as an info in the README

**Comment by g3rd** [comment]
@benedom thank you!
