### ISSUE TITLE
Delay in magnification gesture

### ISSUE THREAD

**Issue by guidove** [benedom/SwiftyCrop#14]
I am noticing a delay in the magnification gesture. 

Steps to reproduce: 
1. Pinch-zoom out, but leave your fingers on the screen. 
2. Then, without lifting your fingers, pinch-zoom in. 

Expected result:
- At step 2, image starts to scale down / get smaller immediately

Actual result:
- At step 2, image first scales a litlle up. I have to continue pinch-zoom-in until finally the image starts to scale down / get smaller again.

I'm not sure this is a bug in MagnificationGesture? This SO thread seems to suggest this: https://stackoverflow.com/questions/69634258/swiftui-magnificationgesture-delay (check comment on only answer)
If so, I guess there's nothing you can do.

**Comment by benedom** [comment]
@guidove It seems like the delay only exists when leaving the fingers on the screen after zooming all the way out? At least that's how I could reproduce it. When I remove my fingers after zooming out and put them on to zoom in again, I do not notice a delay.
