### ISSUE TITLE
Add version tag

### ISSUE THREAD

**Issue by daveddm** [benedom/SwiftyCrop#20]
Hi,
I was wondering if you could add a version tag for the most recent revision. Currently when using your package through SPM the only options are to pin to the branch or to a specific commit. This causes issues if SwiftyCrop is a dependency of another package that is using version based pinning:

>A branch-based requirement
>
>Select the name of the branch for your package dependency to follow. Use branch-based dependencies when you're developing multiple packages in tandem or when you don't want to publish versions of your package dependencies.
>
>Note that packages which use branch-based dependency requirements can't be added as dependencies to packages that use >version-based dependency requirements; you should remove branch-based dependency requirements before publishing a version of your package.
>
>A commit-based requirement
>
>Select the commit hash for your package dependency to follow. Choosing this option isn't recommended, and should be limited to exceptional cases. While pinning your package dependency to a specific commit ensures that the package dependency doesn't change and your code remains stable, you don't receive any updates at all. If you worry about the stability of a remote package, consider one of the more restrictive options of the version-based requirement.
>
>Packages which use commit-based dependency requirements can't be added as dependencies to packages that use version-based dependency requirements; you should remove commit-based dependency requirements before publishing a version of your package.

https://github.com/swiftlang/swift-package-manager/blob/main/Documentation/PackageDescription.md#:~:text=A%20branch%2Dbased%20requirement,commit%2Dbased%20dependency%20requirements%20before%20publishing%20a%20version%20of%20your%20package.

Thanks for your work on this package.

**Comment by benedom** [comment]
Done, added a tag for the current and all upcoming versions
