### ISSUE TITLE
Image cropping for landscape images is buggy

### ISSUE THREAD

**Issue by cvb941** [benedom/SwiftyCrop#7]
I need to disable scaling in addition to disabling rotation.

My use case is to crop rectangular photos to squares.
Right now, after opening the crop window, the image is already cropped a bit:
![image](https://github.com/benedom/SwiftyCrop/assets/2351527/6fa273b5-7b8f-4982-a63b-6025e73390d3)

I would like to prevent users from having to zoom out by default, it would be great if the square crop was as large as it can be (and potentially allow the user to zoom in if they want to).

A solution could either introduce a `scaleImage` boolean parameter, or add a `minMagnificationScale` parameter.

**Comment by cvb941** [comment]
Hi @benedom,

Thanks for your reply.

I have implemented your suggestions. While the solution works on portrait pictures, unfortunately the behaviour is quite buggy on landscape oriented photos.

You can try it out for yourself in your demo app, if you load any landscape photo, such as `https://picsum.photos/2000/1000`

**Comment by benedom** [comment]
Hi @cvb941 thanks for pointing this issue out. It seems like there is a general issue when cropping a landscape image, the mask does not clip correctly and the gestures are jumpy. I will open this as a issue to fix.

**Comment by benedom** [comment]
Reproducible by changing the loaded image size in the demo app to a landscape format, e.g. by changing the loading URL to `https://picsum.photos/2000/1000`

**Comment by cvb941** [comment]
Hi, I have fixed what I needed in my fork and opened up a pull request for you to merge or get started with :)

**Comment by benedom** [comment]
Thanks @cvb941 for the fix!
