### ISSUE TITLE
Getting Cannot find type 'CIFilter' in scope error 

### ISSUE THREAD

**Issue by fawkeswei** [benedom/SwiftyCrop#9]
Tried to add SwiftyCrop as dependency of a Swift package, when building got this error 

SwiftyCrop/Sources/SwiftyCrop/Models/CropViewModel.swift:227:19: Cannot find type 'CIFilter' in scope

**Comment by benedom** [comment]
Hi, CIFilter should be part of UIKit and its import inside the CropViewModel (https://developer.apple.com/documentation/coreimage/cifilter). What Xcode version are you using to build and what platform are you building for?

**Comment by fawkeswei** [comment]
My bad, it was added to a shared target that was used in watch os target causing the issue.
